language: node_js
node_js:
  - "10.1.0"
sudo: false
cache:
  directories:
    - $HOME/.yarn-cache
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script:
  - travis_retry npm install -g yarn
  - yarn test
  - yarn bundle:ios